sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t thusimon/dockeria-app-workflow:latest -f ./app-workflow/Dockerfile.dev ./app-workflow

script:
  - docker run -e CI=true thusimon/dockeria-app-workflow:latest npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockeria-app-workflow"
  env: "Dockeriaappworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-683418073496"
  bucket_path: "dockeria-app-workflow"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
