sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t thusimon/dockeria-app-workflow:latest -f app-workflow/Dockerfile.dev .

script:
  - docker run -e CI=true thusimon/dockeria-app-workflow:latest npm run test
