sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t thusimon/dockeria-app-workflow:latest -f ./app-workflow/Dockerfile.dev ./app-workflow

script:
  - docker run -e CI=true thusimon/dockeria-app-workflow:latest npm run test

after_success:
  - docker build -t thusimon/dockeria-app-workflow-prod:latest ./app-workflow
  # login to docker CLI
  - echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
  # upload prod images to docker hub
  - docker push thusimon/dockeria-app-workflow-prod:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockeria-app-workflow"
  env: "Dockeriaappworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-683418073496"
  bucket_path: "dockeria-app-workflow"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main
