version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: thusimon/app-workflow:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
