apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: thusimon/fibo-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # the host name should be the cluster ip service name
            - name: REDIS_PORT
              value: '6379'
